Sun
fslzrr/among-us pull request #9
Opened 2020-11-17 23:41 UTC by marsofi

Added sunlight, sun and party hat object.
Used textures and PointLights

2020-11-18 00:27 UTC, fslzrr requested changes
En general todo se ve bieen, nomas se te fueron unos comments y los archivos de DS_store

2020-11-18 00:27 UTC, fslzrr commented on package.json
> +    "parcel-bundler": "^1.3.1",
Por que actualizaste el bundler? Digo, no hay pedo pero me dio la duda jajajaja

2020-11-18 00:27 UTC, fslzrr commented on src/core/setup.ts
> +  light.color.setHSL(0.08, 0.8, 0.5);
Maybe podriamos mover el color y la creando de la luz hacia adentro del archivo del sol y solo poner la posición aquí

2020-11-18 00:27 UTC, fslzrr commented on src/shapes/cube.ts
> +// const material = new MeshLambertMaterial({ color: 0x00ff00 });
No comments in this repo :)

2020-11-18 00:27 UTC, fslzrr commented on src/shapes/party_hat.ts
> +);
Cooool

2020-11-18 00:27 UTC, fslzrr commented on src/shapes/party_hat.ts
> +// const texture = new TextureLoader().load( '../textures/sun.jpg' );
El comment 🙂

2020-11-18 00:27 UTC, fslzrr commented on src/shapes/sun.ts
> +// const texture = new TextureLoader().load( '../textures/sun.jpg' );
Comment

2020-11-18 17:12 UTC, marsofi commented on package.json
> +    "parcel-bundler": "^1.3.1",
Actualicé todo mi environment a lo más nuevo y creo que se actualizo con eso

2020-11-18 17:47 UTC, marsofi commented on src/core/setup.ts
> +  light.color.setHSL(0.08, 0.8, 0.5);
listoo

2020-11-18 17:47 UTC, marsofi commented on src/shapes/cube.ts
> +// const material = new MeshLambertMaterial({ color: 0x00ff00 });
yes sir

2020-11-19 04:01 UTC, fslzrr approved these changes
LGTM

2020-11-19 04:17 UTC, merged